spring:
  datasource:
    username: postgres
    password: jesussaves
    url: jdbc:postgresql://localhost:5432/book_social_network
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable=true
          auth: true
#          timeout: 3000
#          connectiontimeout: 5000
#          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY}
      expiration: ${JWT_EXPIRATION}
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088