spring:
  datasource:
    username: postgres
    password: jesussaves
    url: jdbc:postgresql://localhost:5432/book_social_network
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: fileserverapplication@gmail.com
    password: llkfamepyeexragd
    properties:
      mail:
        smtp:
          starttls:
            enable=true
          auth: true
          timeout: 3000
          connectiontimeout: 5000
          writetimeout: 5000